version: '3.3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./production:/production
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
      build: .
      expose:
      - 9000
      environment:
        XDEBUG_MODE: debug
        XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      volumes:
        - ./production:/production